services:
  pyjdb:
    build: .
    container_name: pyjdb

    ports:
      - "8000:8000"

    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

    # restart-safe
    restart: unless-stopped

    # persistency
    volumes:
      # database files (namespace/document JSONs)
      - ./data/:/app/data

    working_dir: /app
